import { contacts, phoneHref, withOfferMessage } from './data/contacts.js';
import { faq } from './data/asset.js';
import imageManifest from './data/image-manifest.js';
import { investorHero, diligence, economics } from './sections-investment.js';
const arrow = '<span aria-hidden="true">↗</span>';
const presentation = withOfferMessage(contacts.whatsappUrl, 'презентация земельного массива 6,2 га за 55 млн рублей в «Новом Бородино»');
const materials = withOfferMessage(contacts.whatsappUrl, 'материалы для проверки земельного массива 6,2 га в «Новом Бородино»');
const viewing = withOfferMessage(contacts.whatsappUrl, 'просмотр земельного массива 6,2 га в «Новом Бородино»');
const nav = '<a href="#asset">Об объекте</a><a href="#concept">Схема</a><a href="#facts">Проверка</a><a href="#scenarios">Экономика</a><a href="#location">Локация</a>';
const brand = '<span>НБ</span><b>Новое<br>Бородино</b>';
const external = 'target="_blank" rel="noopener noreferrer"';
const photo = (src, alt, width = 1800, height = 1350) => {
  const image = imageManifest[src] || { width, height };
  const sizes = src.startsWith('actual-gallery/') ? '(max-width:760px) 84vw, 48vw' : '(max-width:760px) 88vw, 72vw';
  return `<img src="/images/${src}.webp" ${image.small ? `srcset="${image.small} ${image.smallWidth}w, /images/${src}.webp ${image.width}w" sizes="${sizes}"` : ''} alt="${alt}" loading="lazy" decoding="async" width="${image.width}" height="${image.height}">`;
};
const controls = (label) => `<div class="conveyor-controls"><span>${label}</span><div><button type="button" data-conveyor-prev aria-label="Предыдущий кадр">‹</button><button type="button" data-conveyor-pause aria-pressed="false">Пауза</button><button type="button" data-conveyor-next aria-label="Следующий кадр">›</button></div></div>`;
const gallery = ['Внутренняя территория — вид 1','Внутренняя территория — вид 2','Внутренняя территория — вид 3','Внутренняя территория — вид 4','Внутренняя территория — вид 5','Въезд на территорию','Лес рядом с территорией','Можайское водохранилище','Можайское водохранилище — вид 2','Подъезд к территории'];
export const landingMarkup = () => `
<a class="skip-link" href="#content">Перейти к содержимому</a>
<header class="lot-header" data-lot-header><div class="lot-container lot-header__inner"><a class="lot-brand" href="#top" aria-label="НБ Новое Бородино — главная">${brand}</a><nav class="lot-nav" aria-label="Навигация по странице">${nav}</nav><a class="lot-header__phone" href="${phoneHref}" data-contact-channel="phone">${contacts.phone}<small>Екатерина · 09:00–20:00</small></a><button class="lot-header__cta" type="button" data-contact-choice-open data-contact-context="materials">Получить материалы</button><button class="lot-menu" data-lot-menu type="button" aria-expanded="false" aria-controls="lot-mobile-menu">Меню <span aria-hidden="true">☰</span></button></div><nav class="lot-mobile-nav" id="lot-mobile-menu" hidden aria-label="Мобильная навигация">${nav}<a href="${phoneHref}" data-contact-channel="phone">Позвонить Екатерине</a></nav></header>
<button class="lot-sticky-cta" type="button" data-sticky-cta data-contact-choice-open data-contact-context="materials" data-event="contact_options" hidden>Запросить материалы ${arrow}</button>
<div class="mobile-contact-bar" data-mobile-contact-bar hidden><button type="button" data-contact-choice-open data-contact-context="materials">Запросить документы</button><a href="${phoneHref}" data-contact-channel="phone">Позвонить ↗</a></div>
<dialog class="contact-choice" data-contact-choice aria-labelledby="contact-choice-title"><button type="button" data-contact-choice-close>Закрыть ×</button><p class="lot-kicker">Связаться напрямую</p><h2 id="contact-choice-title">Выберите удобный канал</h2><p data-contact-choice-copy>Подготовлен короткий запрос документов и схемы.</p><div class="contact-choice__links"><a href="${materials}" ${external} data-choice-channel="whatsapp" data-contact-channel="whatsapp">WhatsApp ↗</a><a href="${contacts.telegramUrl}" ${external} data-choice-channel="telegram" data-contact-channel="telegram">Telegram ↗</a><a href="${contacts.maxUrl}" ${external} data-contact-channel="max">MAX ↗</a><a href="${phoneHref}" data-contact-channel="phone">Позвонить ↗</a></div><small>Сообщение откроется во внешнем приложении. Сайт не получает и не хранит ваши данные.</small></dialog>
<main id="content">
${investorHero}

<section class="lot-section lot-asset" id="asset" aria-labelledby="asset-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">01 / Состав предложения</p><h2 id="asset-title">Масштаб — в целом.<br><em>Ясность — в деталях.</em></h2></div><p>В одном предложении объединены участки и внутренняя дорожная сеть. Вы рассматриваете территорию целиком и обсуждаете покупку с одним собственником.</p></div><dl class="asset-metrics"><div><dt>6,2 <small>га</small></dt><dd>общая площадь массива</dd></div><div><dt>5,2 <small>га</small></dt><dd>71 участок под застройку</dd></div><div><dt>1 <small>га</small></dt><dd>внутренние дороги</dd></div><div><dt>55 <small>млн ₽</small></dt><dd>стоимость единого лота</dd></div></dl><div class="asset-summary"><p>Стоимость включает земельный массив в указанном составе. Бюджет строительства и инженерной подготовки будущего проекта рассчитывается отдельно.</p><a class="lot-text-link" href="#concept">Посмотреть схему ${arrow}</a></div></div></section>

<section class="lot-section lot-concept" id="concept" aria-labelledby="concept-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">02 / Схема массива</p><h2 id="concept-title">Территория<br><em>в едином контуре.</em></h2></div><p>71 участок общей площадью 5,2 га и 1 га внутренних дорог образуют единый продаваемый актив.</p></div></div><div class="lot-concept__full" data-concept-canvas>${photo('concept-scheme','Схема состава земельного массива с красным контуром',1980,1106)}</div><div class="lot-container lot-concept__caption"><p><b>Важно:</b> исходная схема содержит прежнюю подпись «74 участка». Актуальный заявленный состав — 71 участок и дороги; перед сделкой его необходимо сверить с кадастровым реестром.</p><button class="lot-text-link" type="button" data-concept-open data-event="masterplan_open">Открыть и увеличить схему ${arrow}</button></div></section>

<section class="lot-section lot-context" id="territory" aria-labelledby="territory-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">02 / Территория с высоты</p><h2 id="territory-title">Увидеть место.<br><em>Оценить масштаб.</em></h2></div><p>Аэрофотографии помогают понять планировку, подъезды и окружение. Границы продаваемого лота показаны отдельно на схеме.</p></div></div><div data-conveyor><div class="territory-slider" data-conveyor-window tabindex="0" role="region" aria-label="Аэрофотографии территории"><div class="conveyor-track" data-conveyor-track>${[1,2,3,4,5,6].map(n=>`<figure>${photo(`territory/territory-slide-0${n}`,`Аэрофотография Нового Бородино — вид ${n}`,1600,1080)}</figure>`).join('')}</div></div><div class="lot-container">${controls('6 аэрофотографий · листайте или перетаскивайте')}</div></div></section>

${diligence}

<section class="lot-section lot-materials" id="materials" aria-labelledby="materials-title"><div class="lot-container lot-materials__inner"><div><p class="lot-kicker">Для предметного разговора</p><h2 id="materials-title">Сначала материалы.<br><em>Затем решение.</em></h2><p>Получите сведения о составе лота и подготовьте вопросы к разговору с Екатериной. Документы передаются напрямую, без заполнения заявки на сайте.</p></div><div><ul class="materials-list"><li>Кадастровые сведения и выписки</li><li>Схема массива и документы на дороги</li><li>Технические условия электроснабжения</li><li>Материалы Минкульта и археологии</li></ul><button class="lot-button lot-button--accent" type="button" data-contact-choice-open data-contact-context="materials" data-event="materials_request">Получить документы и схему ${arrow}</button><p class="action-note">Выберите WhatsApp, Telegram, MAX или телефон. Актуальный состав пакета уточнит Екатерина.</p></div></div></section>

<section class="lot-section lot-render-conveyor" id="visualizations" aria-labelledby="visualizations-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">05 / Возможный сценарий</p><h2 id="visualizations-title">Место для<br><em>вашей архитектуры.</em></h2></div><p>Один из вариантов развития — коттеджный проект с общей архитектурой и внутренними улицами. Визуализации показывают концепцию, а не существующую застройку.</p></div></div><div data-conveyor><div class="render-conveyor" data-conveyor-window tabindex="0" role="region" aria-label="Визуализации возможного развития"><div class="conveyor-track" data-conveyor-track>${['1','2','3','4','5','6','7','8','9','10','11','12','12-2','13','14'].map(n=>`<figure>${photo(`renders/${n}`,`Возможный архитектурный сценарий — кадр ${n}`,1920,1080)}</figure>`).join('')}</div></div><div class="lot-container">${controls('Концепция развития · 15 визуализаций')}<p class="render-conveyor__note">Архитектурные решения, этапы и экономика проекта определяются покупателем после проверки правовых и технических условий.</p></div></div></section>

${economics}

<section class="lot-section lot-section--paper" id="actual" aria-labelledby="actual-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">06 / Территория сегодня</p><h2 id="actual-title">Реальные фотографии.<br><em>Настоящий контекст.</em></h2></div><p>Внутренняя территория, подъезд и природное окружение. Нажмите на фотографию, чтобы рассмотреть детали.</p></div></div><div class="actual-slider" data-actual-slider role="region" aria-label="Фотографии территории и окружения"><div class="actual-slider__viewport"><div class="actual-slider__track" data-actual-track>${gallery.map((label,i)=>`<figure><button type="button" data-photo-open aria-label="Открыть: ${label}">${photo(`actual-gallery/actual-${String(i+1).padStart(2,'0')}`,label)}<span class="photo-caption">${label}</span></button></figure>`).join('')}</div></div><div class="lot-container actual-slider__controls"><button type="button" data-actual-prev aria-label="Предыдущее фото">‹</button><span data-actual-count aria-live="off">01 / 10</span><button type="button" data-actual-pause aria-pressed="false">Пауза</button><button type="button" data-actual-next aria-label="Следующее фото">›</button></div></div><div class="lot-container gallery-next"><a class="lot-text-link" href="#location">Посмотреть расположение ${arrow}</a></div></section>

<section class="lot-location" id="location" aria-labelledby="location-title"><div class="lot-location__grid"><div class="lot-location__editorial"><p class="lot-kicker">07 / Локация</p><h2 id="location-title">Подмосковье.<br><em>Можайский район.</em></h2><p>Деревня Новомихайловка, Новое Бородино. Западное направление от Москвы, рядом с Можайским водохранилищем.</p><ul class="location-context"><li>1,5–2 км до побережья — по сведениям собственника.</li><li>Лесное окружение и исторические места Бородинского края.</li><li>Бытовая инфраструктура — в окрестных населённых пунктах и Можайске.</li></ul><p></p><dl><div><dt>105 <small>км</small></dt><dd>от МКАД</dd></div><div><dt>20 <small>км</small></dt><dd>до Можайска</dd></div></dl><p class="action-note">Расстояния по материалам проекта. Время в пути зависит от маршрута и дорожной ситуации.</p><div class="lot-location__actions"><a class="lot-button lot-button--accent" href="${viewing}" ${external} data-contact-channel="whatsapp" data-event="lead_site_visit">Договориться о просмотре ${arrow}</a><a class="lot-text-link lot-text-link--light" href="https://yandex.ru/maps/?rtext=~55.602600%2C35.720800&amp;rtt=auto" ${external} data-event="route_open">Построить маршрут ${arrow}</a></div></div><div class="lot-map" data-lot-map><img src="/images/location-map-yandex.webp" alt="Москва, Можайск и расположение Нового Бородино на карте" loading="lazy" width="650" height="450"><button class="lot-button lot-button--dark map-activate" data-map-activate type="button">Открыть интерактивную карту ${arrow}</button><iframe title="Расположение Нового Бородино на Яндекс Картах" data-src="https://yandex.ru/map-widget/v1/?ll=35.720800%2C55.602600&amp;z=12&amp;pt=35.720800%2C55.602600%2Cpm2rdm" hidden></iframe><p class="map-status" data-map-status hidden>Карта загружается. Если она недоступна, воспользуйтесь ссылкой «Построить маршрут».</p></div></div></section>

<section class="lot-section lot-faq" id="questions" aria-labelledby="faq-title"><div class="lot-container lot-faq__grid"><div><p class="lot-kicker">Перед первым разговором</p><h2 id="faq-title">Важные<br><em>вопросы.</em></h2></div><div>${faq.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>

<section class="lot-contact" id="contacts" aria-labelledby="contact-title"><div class="lot-container lot-contact__inner"><div><p class="lot-kicker">08 / Личный контакт</p><h2 id="contact-title">Обсудим территорию<br><em>и ваши планы.</em></h2><p>Екатерина Хабарова — контактное лицо по объекту. Запросите презентацию, задайте вопросы о составе массива или выберите время просмотра.</p><ol class="contact-steps"><li><span>01</span>Разговор о ваших задачах</li><li><span>02</span>Материалы и проверка состава</li><li><span>03</span>Просмотр на месте и обсуждение условий</li></ol></div><div class="contact-card"><p class="contact-card__name">Екатерина Хабарова</p><p>По вопросам покупки массива</p><a class="contact-phone" href="${phoneHref}" data-contact-channel="phone">${contacts.phone}</a><p class="action-note">Ежедневно, 09:00–20:00</p><a class="lot-button lot-button--accent" href="${phoneHref}" data-contact-channel="phone" data-event="phone_click">Позвонить Екатерине ${arrow}</a><div class="contact-messengers"><a href="${presentation}" ${external} data-contact-channel="whatsapp">WhatsApp ↗</a><a href="${withOfferMessage(contacts.telegramUrl, 'обсуждение массива 6,2 га и времени звонка')}" ${external} data-contact-channel="telegram">Telegram ↗</a><a href="${contacts.maxUrl}" ${external} data-contact-channel="max">MAX ↗</a></div><p class="action-note">Удобнее позже? Напишите в мессенджере и предложите время для звонка.</p></div></div></section>
</main><footer class="lot-footer"><div class="lot-container lot-footer__inner"><a class="lot-brand" href="#top">${brand}</a><p>6,2 га · 55 млн ₽<br>Продажа единым лотом</p><a href="/cookie-i-analitika/">Cookie и аналитика</a><button type="button" data-cookie-settings hidden>Настроить аналитику</button><span>© 2026 Новое Бородино</span></div></footer>
<dialog class="lot-lightbox" data-lightbox-dialog aria-label="Просмотр изображения"><button type="button" aria-label="Закрыть просмотр" data-lightbox-close>×</button><figure><img alt="" data-lightbox-image><figcaption data-lightbox-caption></figcaption></figure></dialog>`;
