import { contacts, phoneHref, withOfferMessage } from './data/contacts.js';
import { faq } from './data/asset.js';
import imageManifest from './data/image-manifest.js';
import { investorHero, diligence } from './sections-investment.js';
const arrow = '<span aria-hidden="true">↗</span>';
const presentation = withOfferMessage(contacts.whatsappUrl, 'презентация земельного массива 6,2 га за 55 млн рублей в «Новом Бородино»');
const materials = withOfferMessage(contacts.whatsappUrl, 'материалы земельного массива 6,2 га в «Новом Бородино»');
const viewing = withOfferMessage(contacts.whatsappUrl, 'просмотр земельного массива 6,2 га в «Новом Бородино»');
const nav = '<a href="#asset">Об объекте</a><a href="#concept">Схема</a><a href="#facts">Документы</a><a href="#location">Локация</a>';
const brand = '<span>НБ</span><b>Новое<br>Бородино</b>';
const external = 'target="_blank" rel="noopener noreferrer"';
const asset = (path) => `${process.env.SITE_BASE || '/'}images/${path}`;
const photo = (src, alt, width = 1800, height = 1350) => {
  const image = imageManifest[src] || { width, height };
  const sizes = src.startsWith('actual-gallery/') ? '(max-width:760px) 84vw, 48vw' : '(max-width:760px) 88vw, 72vw';
  return `<img src="${asset(`${src}.webp`)}" ${image.small ? `srcset="${asset(image.small.replace('/images/',''))} ${image.smallWidth}w, ${asset(`${src}.webp`)} ${image.width}w" sizes="${sizes}"` : ''} alt="${alt}" loading="lazy" decoding="async" width="${image.width}" height="${image.height}">`;
};
const gallery = [
  ['2026-01','Внутренняя территория'],['2026-02','Внутренняя территория'],['2026-03','Внутренняя территория'],['2026-04','Внутренняя территория'],['2026-05','Внутренняя территория'],['2026-06','Внутренняя территория'],['2026-07','Внутренняя территория'],['2026-08','Въезд на территорию'],['2026-09','Лес рядом с территорией'],['2026-10','Можайское водохранилище'],['2026-11','Можайское водохранилище'],['2026-12','Можайское водохранилище'],['2026-13','Подъезд к территории'],['2026-14','Можайское водохранилище'],
];
export const landingMarkup = () => `
<a class="skip-link" href="#content">Перейти к содержимому</a>
<header class="lot-header" data-lot-header><div class="lot-container lot-header__inner"><a class="lot-brand" href="#top" aria-label="НБ Новое Бородино — главная">${brand}</a><nav class="lot-nav" aria-label="Навигация по странице">${nav}</nav><div class="lot-header__contacts"><a class="lot-header__phone" href="${phoneHref}" data-contact-channel="phone">${contacts.phone}<small>Отдел продаж · 09:00–20:00</small></a><button class="lot-header__cta" type="button" data-contact-choice-open data-contact-context="materials">Контакты</button></div><button class="lot-menu" data-lot-menu type="button" aria-expanded="false" aria-controls="lot-mobile-menu">Меню <span aria-hidden="true">☰</span></button></div><nav class="lot-mobile-nav" id="lot-mobile-menu" hidden aria-label="Мобильная навигация">${nav}<a href="${phoneHref}" data-contact-channel="phone">Позвонить в отдел продаж</a></nav></header>
<button class="lot-sticky-cta" type="button" data-sticky-cta data-contact-choice-open data-contact-context="materials" data-event="contact_options" hidden>Запросить материалы ${arrow}</button>
<div class="mobile-contact-bar" data-mobile-contact-bar hidden><button type="button" data-contact-choice-open data-contact-context="materials">Запросить документы</button><a href="${phoneHref}" data-contact-channel="phone">Позвонить ↗</a></div>
<dialog class="contact-choice" data-contact-choice aria-labelledby="contact-choice-title"><button type="button" data-contact-choice-close>Закрыть ×</button><p class="lot-kicker">Связаться напрямую</p><h2 id="contact-choice-title">Выберите удобный способ связи</h2><div class="contact-choice__links"><a href="${materials}" ${external} data-choice-channel="whatsapp" data-contact-channel="whatsapp">WhatsApp ↗</a><a href="${contacts.telegramUrl}" ${external} data-choice-channel="telegram" data-contact-channel="telegram">Telegram ↗</a><a href="${contacts.maxUrl}" ${external} data-contact-channel="max">MAX ↗</a><a href="${phoneHref}" data-contact-channel="phone">Позвонить ↗</a></div><small>Сообщение откроется во внешнем приложении. Сайт не получает и не хранит ваши данные.</small></dialog>
<main id="content">
${investorHero}

<section class="lot-section lot-asset functional" id="asset" aria-labelledby="asset-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">01 / Состав предложения</p><h2 id="asset-title">Единый актив.<br>Понятный состав.</h2></div><p>В одном предложении объединены 71 участок площадью 5,2 га и 1 га внутренних дорог. Массив продаётся целиком одним лотом.</p></div><dl class="asset-metrics"><div><dt>6,2 <small>га</small></dt><dd>общая площадь массива</dd></div><div><dt>5,2 <small>га</small></dt><dd>71 участок под застройку</dd></div><div><dt>1 <small>га</small></dt><dd>внутренние дороги</dd></div><div><dt>55 <small>млн ₽</small></dt><dd>стоимость единого лота</dd></div></dl><div class="asset-summary"><a class="lot-text-link" href="#concept">Посмотреть структуру массива ↓</a></div></div></section>

<section class="lot-section lot-concept functional" id="concept" aria-labelledby="concept-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">02 / Схема массива</p><h2 id="concept-title">71 участок.<br>Один контур сделки.</h2></div><p>71 участок общей площадью 5,2 га и 1 га внутренних дорог образуют единый продаваемый актив. Площадь участков — от 5 до 10 соток. Продаваемая территория на схеме выделена красным контуром.</p></div></div><div class="lot-concept__full" data-concept-canvas>${photo('concept-scheme-v3','Схема состава земельного массива: продаваемая территория выделена красным контуром',1980,1106)}</div><div class="lot-container lot-concept__caption"><button class="lot-text-link" type="button" data-concept-open data-event="masterplan_open">Открыть крупно ${arrow}</button><a class="section-next" href="#territory">Увидеть территорию с высоты ↓</a></div></section>

<section class="lot-section lot-context" id="territory" aria-labelledby="territory-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">Территория с высоты</p><h2 id="territory-title">Увидеть место.<br><em>Оценить масштаб.</em></h2></div><p>Три актуальные аэрофотографии показывают территорию, внутреннюю дорожную структуру, подъезд и окружение массива.</p></div></div><div data-conveyor><div class="territory-slider" data-conveyor-window tabindex="0" role="region" aria-label="Аэрофотографии территории"><div class="conveyor-track" data-conveyor-track>${[1,2,3].map(n=>`<figure>${photo(`territory/territory-slide-2026-0${n}`,`Аэрофотография Нового Бородино — вид ${n}`,2400,1350)}</figure>`).join('')}</div></div></div></section>

${diligence}

<section class="lot-section lot-materials functional" id="materials" aria-labelledby="materials-title"><div class="lot-container lot-materials__inner"><div><p class="lot-kicker">Для предметного разговора</p><h2 id="materials-title">Ключевые документы<br>в одном пакете.</h2><p>Получите документы и исходные данные по объекту до разговора о просмотре и условиях сделки.</p></div><div><ul class="materials-list"><li><strong>Выписки из ЕГРН</strong><span>права и характеристики участков</span></li><li><strong>ГПЗУ</strong><span>градостроительные параметры участков</span></li><li><strong>Заключение Роснедр</strong><span>об отсутствии полезных ископаемых в недрах</span></li><li><strong>Минкультура</strong><span>государственная историко-культурная экспертиза участка</span></li><li><strong>Археологические материалы</strong><span>результаты обследования и шурфования</span></li></ul><button class="lot-button lot-button--accent" type="button" data-contact-choice-open data-contact-context="materials" data-event="materials_request">Получить пакет документов ${arrow}</button><p class="action-note">WhatsApp · Telegram · MAX · телефон</p></div></div><div class="lot-container"><a class="section-next" href="#visualizations">Документы дают факты. Визуализации показывают потенциал. ↓</a></div></section>

<section class="lot-section lot-render-conveyor" id="visualizations" aria-labelledby="visualizations-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">05 / Возможный сценарий</p><h2 id="visualizations-title">Один из сценариев<br><em>развития территории.</em></h2></div><p>Визуализации показывают возможную организацию коттеджного проекта с единой архитектурой и внутренними улицами. Концепцию и параметры реализации определяет будущий владелец проекта.</p></div></div><div data-conveyor><div class="render-conveyor" data-conveyor-window tabindex="0" role="region" aria-label="Визуализации возможного развития"><div class="conveyor-track" data-conveyor-track>${['1','2','3','4','5','6','7','8','9','10','11','12','12-2','13','14'].map(n=>`<figure>${photo(`renders/${n}`,`Возможный архитектурный сценарий — кадр ${n}`,1920,1080)}</figure>`).join('')}</div></div></div></section>

<section class="lot-location" id="location" aria-labelledby="location-title"><div class="lot-location__grid"><div class="lot-location__editorial"><p class="lot-kicker">07 / Локация</p><h2 id="location-title">Подмосковье.<br>Можайский район.</h2><p>Новое Бородино — западное направление Московской области, рядом с Можайским водохранилищем и Можайском.</p><ul class="location-context"><li>1,5–2 км до побережья Можайского водохранилища.</li><li>Лесное окружение и исторические места Бородинского края.</li><li>Бытовая инфраструктура — в окрестных населённых пунктах и Можайске.</li></ul><dl><div><dt>105 <small>км</small></dt><dd>от МКАД</dd></div><div><dt>30 <small>км</small></dt><dd>до Можайска</dd></div></dl><div class="lot-location__actions"><button class="lot-button lot-button--accent" type="button" data-contact-choice-open data-contact-context="viewing" data-event="lead_site_visit">Обсудить детали ${arrow}</button><a class="lot-text-link lot-text-link--light" href="https://yandex.ru/maps/?rtext=~55.602600%2C35.720800&amp;rtt=auto" ${external} data-event="route_open">Построить маршрут ${arrow}</a><a class="section-next" href="#actual">Посмотреть территорию сегодня ↓</a></div></div><div class="lot-map" data-lot-map><img src="${asset('location-map-yandex.webp')}" alt="Москва, Можайск и расположение Нового Бородино на карте" loading="lazy" width="650" height="450"><iframe title="Расположение Нового Бородино на Яндекс Картах" src="https://yandex.ru/map-widget/v1/?ll=35.720800%2C55.602600&amp;z=12&amp;pt=35.720800%2C55.602600%2Cpm2rdm"></iframe></div></div></section>
<section class="lot-section lot-section--paper functional" id="actual" aria-labelledby="actual-title"><div class="lot-container"><div class="lot-heading"><div><p class="lot-kicker">08 / Территория сегодня</p><h2 id="actual-title">Территория сегодня.</h2></div><p>Фотографии показывают внутреннюю территорию, дороги, подъезд, лесное окружение и текущее состояние массива.</p></div></div><div class="actual-slider" data-actual-slider role="region" aria-label="Фотографии территории и окружения"><div class="actual-slider__viewport"><div class="actual-slider__track" data-actual-track>${gallery.map(([number,label])=>`<figure><button type="button" data-photo-open aria-label="Открыть: ${label}">${photo(`actual-gallery/actual-${number}`,label)}<span class="photo-caption">${label}</span></button></figure>`).join('')}</div></div><div class="lot-container actual-slider__controls"><button type="button" data-actual-prev aria-label="Предыдущее фото">‹</button><span data-actual-count aria-live="off">01 / 09</span><button type="button" data-actual-pause aria-pressed="false">Пауза</button><button type="button" data-actual-next aria-label="Следующее фото">›</button></div></div><div class="lot-container gallery-next"><a class="lot-text-link" href="#questions">Ответы на основные вопросы ↓</a></div></section>


<section class="lot-section lot-faq functional" id="questions" aria-labelledby="faq-title"><div class="lot-container lot-faq__grid"><div class="lot-faq__intro"><p class="lot-kicker">Перед первым разговором</p><h2 id="faq-title">Ответы<br>на вопросы.</h2><p>Коротко о составе лота, документах, инфраструктуре и следующем шаге.</p><span>${faq.length} вопросов</span></div><div class="lot-faq__list">${faq.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></div></section>

<section class="lot-contact" id="contacts" aria-labelledby="contact-title"><div class="lot-container lot-contact__inner"><div><p class="lot-kicker">09 / Личный контакт</p><h2 id="contact-title">Документы готовы.<br><em>Следующий шаг — личный разговор.</em></h2><p>Получите материалы, задайте вопросы по объекту и при интересе согласуйте просмотр территории.</p><ol class="contact-steps"><li><span>01</span>Документы и знакомство с объектом</li><li><span>02</span>Предметный разговор о ваших планах</li><li><span>03</span>Просмотр на месте и обсуждение условий</li></ol></div><div class="contact-card"><p class="contact-card__name">Отдел продаж</p><p>По вопросам покупки массива</p><a class="contact-phone" href="${phoneHref}" data-contact-channel="phone">${contacts.phone}</a><p class="action-note">Ежедневно, 09:00–20:00</p><button class="lot-button lot-button--accent" type="button" data-contact-choice-open data-contact-context="materials">Получить консультацию ${arrow}</button><a class="lot-text-link" href="${phoneHref}" data-contact-channel="phone" data-event="phone_click">Позвонить в отдел продаж ${arrow}</a><div class="contact-messengers"><a href="${presentation}" ${external} data-contact-channel="whatsapp">WhatsApp ↗</a><a href="${withOfferMessage(contacts.telegramUrl, 'обсуждение массива 6,2 га и времени звонка')}" ${external} data-contact-channel="telegram">Telegram ↗</a><a href="${contacts.maxUrl}" ${external} data-contact-channel="max">MAX ↗</a></div><p class="action-note">Удобнее позже? Напишите в мессенджере и предложите время для звонка.</p></div></div></section>
</main><footer class="lot-footer"><div class="lot-container lot-footer__inner"><a class="lot-brand" href="#top">${brand}</a><p>6,2 га · 55 млн ₽<br>Продажа единым лотом</p><a href="/cookie-i-analitika/">Cookie и аналитика</a><button type="button" data-cookie-settings hidden>Настроить аналитику</button><span>© 2026 Новое Бородино</span></div></footer>
<dialog class="lot-lightbox" data-lightbox-dialog aria-label="Просмотр изображения"><button type="button" aria-label="Закрыть просмотр" data-lightbox-close>×</button><figure><img alt="" data-lightbox-image><figcaption data-lightbox-caption></figcaption></figure></dialog>`;
